services:
  postgres:
    image: postgres:15
    container_name: saludlink-postgres
    environment:
      POSTGRES_DB: saludlink
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"

  user-service:
    build:
      context: ./services/user-service
    container_name: salud-link-user-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    env_file:
      - ./services/user-service/.env
