version: "3.9"
services:
  create-user:
    image: alex8991/create-user:latest
    ports:
      - "8001:8000"
    environment:
      DB_HOST: 18.215.167.219
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  update-user:
    image: alex8991/update-user:latest
    ports:
      - "8002:8000"
    environment:
      DB_HOST: 18.215.167.219
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  delete-user:
    image: alex8991/delete-user:latest
    ports:
      - "8003:8000"
    environment:
      DB_HOST: 18.215.167.219
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  get-user:
    image: alex8991/get-user:latest
    ports:
      - "8004:8000"
    environment:
      DB_HOST: 18.215.167.219
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres

  auth-user:
    image: alex8991/auth-user:latest
    ports:
      - "8005:8000"
    environment:
      DB_HOST: 18.215.167.219
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: postgres
      DB_PASSWORD: postgres
