version: "3.9"
services:
  db-users:
    image: postgres:15
    container_name: db-users
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql/data

volumes:
  users_data:
