version: '3.8'

services:

  create-user:
    build: ./services/user/create-user
    container_name: create-user
    ports:
      - "8001:8000"
    env_file:
      - ./services/user/create-user/.env

  update-user:
    build: ./services/user/update-user
    container_name: update-user
    ports:
      - "8002:8000"
    env_file:
      - ./services/user/update-user/.env

  delete-user:
    build: ./services/user/delete-user
    container_name: delete-user
    ports:
      - "8003:8000"
    env_file:
      - ./services/user/delete-user/.env

  get-user:
    build: ./services/user/get-user
    container_name: get-user
    ports:
      - "8004:8000"
    env_file:
      - ./services/user/get-user/.env

  auth-user:
    build: ./services/user/auth-user
    container_name: auth-user
    ports:
      - "8005:8000"
    env_file:
      - ./services/user/auth-user/.env

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
