FROM node:20-alpine

# Crear y usar directorio de trabajo
WORKDIR /app

# Copiar solo los archivos necesarios para instalar dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Asegurar que el script se ejecuta correctamente al iniciar
CMD ["node", "kafkaConsumer.js"]
