name: Deploy User Domain to QA

on:
  push:
    paths:
      - 'services/user/**'
      - 'docker-compose.user.yml'
    branches:
      - qa

jobs:
  deploy-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy user service to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_QA_USER }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          source: "./services/user"
          target: "/home/ec2-user/salud-link/services"

      - name: Copy docker-compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_QA_USER }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.user.yml"
          target: "/home/ec2-user/salud-link"

      - name: Run docker-compose on EC2 (USER)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_QA_USER }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/salud-link
            docker compose -f docker-compose.user.yml pull
            docker compose -f docker-compose.user.yml up -d --remove-orphans
