name: Deploy Frontend (QA)

on:
  push:
    branches:
      - qa
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t alex8991/frontend:latest ./frontend
          docker push alex8991/frontend:latest

      - name: Deploy to EC2 Frontend QA
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_QA_FRONTEND }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY_FRONTEND_QA }}
          script: |
            docker rm -f frontend || true
            docker rmi alex8991/frontend:latest || true
            docker pull alex8991/frontend:latest
            docker run -d --name frontend -p 80:80 alex8991/frontend:latest
