name: Deploy Frontend to QA

on:
  push:
    paths:
      - 'docker-compose.frontend.yml'
    branches:
      - qa

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_QA_FRONTEND }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.frontend.yml"
          target: "/home/ec2-user/salud-link"

      - name: Run docker-compose on EC2 (FRONTEND)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_QA_FRONTEND }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/salud-link
            docker compose -f docker-compose.frontend.yml pull
            docker compose -f docker-compose.frontend.yml up -d --remove-orphans
