
name: Deploy Microservicios por Rama

on:
  push:
    branches:
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copiar microservicios a la instancia EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ github.ref == 'refs/heads/qa' && secrets.HOST_QA || secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "./services/user/*"
          target: "/home/ubuntu/salud-link/services/user"

      - name: Ejecutar docker compose según entorno
        uses: appleboy/ssh-action@master
        with:
          host: ${{ github.ref == 'refs/heads/qa' && secrets.HOST_QA || secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/salud-link
            if [ "${GITHUB_REF##*/}" = "main" ]; then
              echo "Desplegando en PRODUCCIÓN"
              docker compose -f docker-compose.prod.yml pull
              docker compose -f docker-compose.prod.yml up -d --remove-orphans
            else
              echo "Desplegando en QA"
              docker compose -f docker-compose.user.yml pull
              docker compose -f docker-compose.user.yml up -d --remove-orphans
            fi
